// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazons3connector.AmazonHelper;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;

public class PutObject extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __awsConfig;
	private amazons3connector.proxies.AwsConfig awsConfig;
	private IMendixObject __region;
	private amazons3connector.proxies.Region region;
	private java.lang.String bucket;
	private java.lang.String key;
	private IMendixObject __file;
	private system.proxies.FileDocument file;

	public PutObject(IContext context, IMendixObject awsConfig, IMendixObject region, java.lang.String bucket, java.lang.String key, IMendixObject file)
	{
		super(context);
		this.__awsConfig = awsConfig;
		this.__region = region;
		this.bucket = bucket;
		this.key = key;
		this.__file = file;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.awsConfig = __awsConfig == null ? null : amazons3connector.proxies.AwsConfig.initialize(getContext(), __awsConfig);

		this.region = __region == null ? null : amazons3connector.proxies.Region.initialize(getContext(), __region);

		this.file = __file == null ? null : system.proxies.FileDocument.initialize(getContext(), __file);

		// BEGIN USER CODE
		S3Client client = AmazonHelper.GetS3Client(awsConfig, region);
		PutObjectRequest req = PutObjectRequest.builder()
				.bucket(bucket)
				.key(key)
				.build();
		
		RequestBody body = RequestBody.fromInputStream(Core.getFileDocumentContent(getContext(), file.getMendixObject()), 
				file.getSize());
		
		client.putObject(req, body);

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "PutObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
