// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import java.io.InputStream;
import amazons3connector.AmazonHelper;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.PutObjectRequest;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JAV_PutObject extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __AwsConfigParam;
	private amazons3connector.proxies.AwsConfig AwsConfigParam;
	private IMendixObject __S3BucketParam;
	private amazons3connector.proxies.S3Bucket S3BucketParam;
	private IMendixObject __S3SummaryObjectParam;
	private amazons3connector.proxies.S3SummaryObject S3SummaryObjectParam;
	private IMendixObject __S3FileDocumentParam;
	private amazons3connector.proxies.S3FileDocument S3FileDocumentParam;

	public JAV_PutObject(IContext context, IMendixObject AwsConfigParam, IMendixObject S3BucketParam, IMendixObject S3SummaryObjectParam, IMendixObject S3FileDocumentParam)
	{
		super(context);
		this.__AwsConfigParam = AwsConfigParam;
		this.__S3BucketParam = S3BucketParam;
		this.__S3SummaryObjectParam = S3SummaryObjectParam;
		this.__S3FileDocumentParam = S3FileDocumentParam;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.AwsConfigParam = __AwsConfigParam == null ? null : amazons3connector.proxies.AwsConfig.initialize(getContext(), __AwsConfigParam);

		this.S3BucketParam = __S3BucketParam == null ? null : amazons3connector.proxies.S3Bucket.initialize(getContext(), __S3BucketParam);

		this.S3SummaryObjectParam = __S3SummaryObjectParam == null ? null : amazons3connector.proxies.S3SummaryObject.initialize(getContext(), __S3SummaryObjectParam);

		this.S3FileDocumentParam = __S3FileDocumentParam == null ? null : amazons3connector.proxies.S3FileDocument.initialize(getContext(), __S3FileDocumentParam);

		// BEGIN USER CODE
		AmazonS3 s3client = AmazonHelper.GetS3Client(AwsConfigParam);
		
		InputStream input = Core.getFileDocumentContent(getContext(), S3FileDocumentParam.getMendixObject());
		
		s3client.putObject(new PutObjectRequest(S3BucketParam.getName(), S3SummaryObjectParam.getKey(),
				input, new ObjectMetadata()));
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "JAV_PutObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
