// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import amazons3connector.AmazonHelper;
import amazons3connector.proxies.S3SummaryObject;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JAV_GetObject extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __AwsConfigParam;
	private amazons3connector.proxies.AwsConfig AwsConfigParam;
	private IMendixObject __S3BucketParam;
	private amazons3connector.proxies.S3Bucket S3BucketParam;
	private java.lang.String S3ObjectKey;

	public JAV_GetObject(IContext context, IMendixObject AwsConfigParam, IMendixObject S3BucketParam, java.lang.String S3ObjectKey)
	{
		super(context);
		this.__AwsConfigParam = AwsConfigParam;
		this.__S3BucketParam = S3BucketParam;
		this.S3ObjectKey = S3ObjectKey;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.AwsConfigParam = __AwsConfigParam == null ? null : amazons3connector.proxies.AwsConfig.initialize(getContext(), __AwsConfigParam);

		this.S3BucketParam = __S3BucketParam == null ? null : amazons3connector.proxies.S3Bucket.initialize(getContext(), __S3BucketParam);

		// BEGIN USER CODE
		AmazonS3 s3client = AmazonHelper.GetS3Client(AwsConfigParam);

		ObjectMetadata metadata = s3client.getObjectMetadata(S3BucketParam.getName(), S3ObjectKey);
		
		if (metadata != null) {
				// create the objects
			S3SummaryObject o = new S3SummaryObject(getContext());
			o.setKey(S3ObjectKey);
			o.setS3Object_S3Bucket(S3BucketParam);
			
			AmazonHelper.enhanceObject(o);
				
			return o.getMendixObject();
		}
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "JAV_GetObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
