// This file was generated by Mendix Modeler 7.2.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazons3connector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the AmazonS3Connector module

	public static java.lang.String getHierarchyDelimiter()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AmazonS3Connector.HierarchyDelimiter");
	}
}