// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazons3connector.proxies;

/**
 * Represents the file metadata as stored in S3
 */
public class S3SummaryObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject s3SummaryObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonS3Connector.S3SummaryObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		FileName("FileName"),
		FolderPath("FolderPath"),
		S3Object_S3Bucket("AmazonS3Connector.S3Object_S3Bucket");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public S3SummaryObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AmazonS3Connector.S3SummaryObject"));
	}

	protected S3SummaryObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject s3SummaryObjectMendixObject)
	{
		if (s3SummaryObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AmazonS3Connector.S3SummaryObject", s3SummaryObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AmazonS3Connector.S3SummaryObject");

		this.s3SummaryObjectMendixObject = s3SummaryObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'S3SummaryObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static amazons3connector.proxies.S3SummaryObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amazons3connector.proxies.S3SummaryObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amazons3connector.proxies.S3SummaryObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazons3connector.proxies.S3SummaryObject(context, mendixObject);
	}

	public static amazons3connector.proxies.S3SummaryObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazons3connector.proxies.S3SummaryObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of FileName
	 */
	public final java.lang.String getFileName()
	{
		return getFileName(getContext());
	}

	/**
	 * @param context
	 * @return value of FileName
	 */
	public final java.lang.String getFileName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FileName.toString());
	}

	/**
	 * Set value of FileName
	 * @param filename
	 */
	public final void setFileName(java.lang.String filename)
	{
		setFileName(getContext(), filename);
	}

	/**
	 * Set value of FileName
	 * @param context
	 * @param filename
	 */
	public final void setFileName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filename)
	{
		getMendixObject().setValue(context, MemberNames.FileName.toString(), filename);
	}

	/**
	 * @return value of FolderPath
	 */
	public final java.lang.String getFolderPath()
	{
		return getFolderPath(getContext());
	}

	/**
	 * @param context
	 * @return value of FolderPath
	 */
	public final java.lang.String getFolderPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FolderPath.toString());
	}

	/**
	 * Set value of FolderPath
	 * @param folderpath
	 */
	public final void setFolderPath(java.lang.String folderpath)
	{
		setFolderPath(getContext(), folderpath);
	}

	/**
	 * Set value of FolderPath
	 * @param context
	 * @param folderpath
	 */
	public final void setFolderPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String folderpath)
	{
		getMendixObject().setValue(context, MemberNames.FolderPath.toString(), folderpath);
	}

	/**
	 * @return value of S3Object_S3Bucket
	 */
	public final amazons3connector.proxies.S3Bucket getS3Object_S3Bucket() throws com.mendix.core.CoreException
	{
		return getS3Object_S3Bucket(getContext());
	}

	/**
	 * @param context
	 * @return value of S3Object_S3Bucket
	 */
	public final amazons3connector.proxies.S3Bucket getS3Object_S3Bucket(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazons3connector.proxies.S3Bucket result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.S3Object_S3Bucket.toString());
		if (identifier != null)
			result = amazons3connector.proxies.S3Bucket.load(context, identifier);
		return result;
	}

	/**
	 * Set value of S3Object_S3Bucket
	 * @param s3object_s3bucket
	 */
	public final void setS3Object_S3Bucket(amazons3connector.proxies.S3Bucket s3object_s3bucket)
	{
		setS3Object_S3Bucket(getContext(), s3object_s3bucket);
	}

	/**
	 * Set value of S3Object_S3Bucket
	 * @param context
	 * @param s3object_s3bucket
	 */
	public final void setS3Object_S3Bucket(com.mendix.systemwideinterfaces.core.IContext context, amazons3connector.proxies.S3Bucket s3object_s3bucket)
	{
		if (s3object_s3bucket == null)
			getMendixObject().setValue(context, MemberNames.S3Object_S3Bucket.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.S3Object_S3Bucket.toString(), s3object_s3bucket.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return s3SummaryObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazons3connector.proxies.S3SummaryObject that = (amazons3connector.proxies.S3SummaryObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AmazonS3Connector.S3SummaryObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
